/**
 * ManifestReel AI — Premium Voice Catalog
 *
 * Curated exclusively from ElevenLabs' PROFESSIONAL tier (human voice-actor /
 * cloned voices) — no generic premade defaults. Every voice_id is unique to a
 * single category (zero reuse) and was validated with a live TTS call.
 *
 * ~150 voices across 8 categories with diverse accents, age ranges and
 * multilingual-capable voices preferred for international expansion.
 *
 * Voice tiers (ElevenLabs model_id):
 *   - flash        → eleven_flash_v2_5      (fast, cheapest)
 *   - turbo        → eleven_turbo_v2_5      (low latency, supports native speed)
 *   - multilingual → eleven_multilingual_v2 (best quality, default)
 *
 * Speed is applied via ElevenLabs' NATIVE `speed` voice setting (0.85 / 1.0 /
 * 1.15) — never FFmpeg atempo — so prosody stays natural.
 */

export type VoiceTier = 'flash' | 'multilingual' | 'turbo';

export interface VoiceEntry {
  id: string;                   // internal ID e.g. "mys-m-01"
  name: string;                 // display name
  elevenLabsId: string;         // ElevenLabs voice_id (professional/shared)
  gender: 'female' | 'male';
  ageRange: 'young' | 'middle' | 'senior';
  accent: string;               // e.g. "American", "British", "Australian"
  language: string;             // primary language
  category: string;             // UI grouping: Female, Male, Mysterious, etc.
  useCases: string[];           // tags: narration, meditation, motivation, etc.
  description: string;          // short character desc e.g. "Deep British narrator, mature"
  defaultTier: VoiceTier;       // recommended tier
  supportedTiers: VoiceTier[];  // all supported tiers
  multilingual: boolean;        // verified in 2+ languages (intl-ready)
  previewUrl: string;           // ElevenLabs-hosted preview (instant card playback)
  samplePath: string;           // legacy local path (unused; live preview/TTS instead)
}

export const VOICE_CATALOG: VoiceEntry[] = [
  { id: 'female-f-01', name: 'Jenny', elevenLabsId: 'dHZt8yoqTSDwjElzgqey', gender: 'female', ageRange: 'young', accent: 'British', language: 'English', category: 'Female', useCases: ['narration', 'advertisement', 'professional', 'manifestation'], description: 'Professional British voice, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/dHZt8yoqTSDwjElzgqey/dW2eOYONBjFv4RZb6FAg.mp3', samplePath: '' },
  { id: 'female-f-02', name: 'Farah', elevenLabsId: '4wf10lgibMnboGJGCLrP', gender: 'female', ageRange: 'young', accent: 'Jordanian', language: 'English', category: 'Female', useCases: ['narration', 'advertisement', 'casual', 'manifestation'], description: 'Casual Jordanian voice, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/fb13b5efe4cb40d39da201b46fac22eb/voices/4wf10lgibMnboGJGCLrP/10Ff0P9ozKLVa4QSSIvC.mp3', samplePath: '' },
  { id: 'female-f-03', name: 'Koraly', elevenLabsId: 'rbFGGoDXFHtVghjHuS3E', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Female', useCases: ['narration', 'advertisement', 'modulated', 'manifestation'], description: 'Modulated American voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/30f4e6eea3604aafaabbb81d16a15d49/voices/rbFGGoDXFHtVghjHuS3E/KkSjTWIViBdnuSG3cWAg.mp3', samplePath: '' },
  { id: 'female-f-04', name: 'Sissi', elevenLabsId: 'Nzx4EODwcRtz5xESEixO', gender: 'female', ageRange: 'middle', accent: 'German', language: 'English', category: 'Female', useCases: ['narration', 'advertisement', 'excited', 'manifestation'], description: 'Excited German voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/JkMtMybti7dSnGjkDsVqAkUgccE3/voices/Nzx4EODwcRtz5xESEixO/W5eZxBezE003A3zLbqkM.mp3', samplePath: '' },
  { id: 'female-f-05', name: 'Blondie', elevenLabsId: 'st7NwhTPEzqo2riw7qWC', gender: 'female', ageRange: 'young', accent: 'British', language: 'English', category: 'Female', useCases: ['narration', 'entertainment_tv', 'hyped', 'manifestation'], description: 'Hyped British voice, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/mkZsm8DEkRXVL0wIvSQqrRam8BH2/voices/st7NwhTPEzqo2riw7qWC/WiTmBD4iXBAuEdaSiwZD.mp3', samplePath: '' },
  { id: 'female-f-06', name: 'Rachel', elevenLabsId: 'aD6riP1btT197c6dACmy', gender: 'female', ageRange: 'middle', accent: 'British', language: 'English', category: 'Female', useCases: ['narration', 'entertainment_tv', 'casual', 'manifestation'], description: 'Casual British voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/aD6riP1btT197c6dACmy/i3sp6HxMHfF6vpeCXxXi.mp3', samplePath: '' },
  { id: 'female-f-07', name: 'Natasha', elevenLabsId: 'PB6BdkFkZLbI39GHdnbQ', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Female', useCases: ['narration', 'entertainment_tv', 'meditative', 'manifestation'], description: 'Meditative American voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/1sQEubbF2LayrwfzcqizACaG7MC3/voices/PB6BdkFkZLbI39GHdnbQ/OsIwp7q9shUryoKFYYMs.mp3', samplePath: '' },
  { id: 'female-f-08', name: 'Labhaoise', elevenLabsId: 'sgk995upfe3tYLvoGcBN', gender: 'female', ageRange: 'young', accent: 'Irish', language: 'English', category: 'Female', useCases: ['narration', 'conversational', 'casual', 'manifestation'], description: 'Casual Irish voice, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/sgk995upfe3tYLvoGcBN/GGzXaNBilHvICIdHpzUd.mp3', samplePath: '' },
  { id: 'female-f-09', name: 'Emily', elevenLabsId: '1cxc5c3E9K6F1wlqOJGV', gender: 'female', ageRange: 'young', accent: 'Irish', language: 'English', category: 'Female', useCases: ['narration', 'narrative_story', 'whispery', 'manifestation'], description: 'Whispery Irish voice, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/6960CkszYQQ8lnmzZIEc29GQFzA2/voices/1cxc5c3E9K6F1wlqOJGV/HPC2o7hJfzll0uTxjsVl.mp3', samplePath: '' },
  { id: 'female-f-10', name: 'Isla', elevenLabsId: 'h8eW5xfRUGVJrZhAFxqK', gender: 'female', ageRange: 'middle', accent: 'Scottish', language: 'English', category: 'Female', useCases: ['narration', 'conversational', 'chill', 'manifestation'], description: 'Chill Scottish voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/h8eW5xfRUGVJrZhAFxqK/aLpZVozKJR2BcBn3Gf9g.mp3', samplePath: '' },
  { id: 'female-f-11', name: 'Eryn', elevenLabsId: 'dj3G1R1ilKoFKhBnWOzG', gender: 'female', ageRange: 'middle', accent: 'US Southern', language: 'English', category: 'Female', useCases: ['narration', 'conversational', 'casual', 'manifestation'], description: 'Casual US Southern voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/DdUt6lVFfrUOSikHrCbs3tesMgE2/voices/dj3G1R1ilKoFKhBnWOzG/P11BkSUnzQicrGBrJ4lA.mp3', samplePath: '' },
  { id: 'female-f-12', name: 'Kylee', elevenLabsId: 'pcKdPWtbF6bM9o7NHjCI', gender: 'female', ageRange: 'middle', accent: 'New Zealand', language: 'English', category: 'Female', useCases: ['narration', 'narrative_story', 'pleasant', 'manifestation'], description: 'Pleasant New Zealand voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/pcKdPWtbF6bM9o7NHjCI/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoiWEJuUUk3Zlo3eVFPTWRGaEJUdVdzOGUydUJmMSIsImZpbGVuYW1lIjoiNzI4Yzc1ZWYtMmQ2Yy00NDkyLThiOTUtZmUwYTQ2NmRlZjdlLm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },
  { id: 'female-f-13', name: 'Emilia', elevenLabsId: 'N8RXoLEWQWUCCrT8uDK7', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Female', useCases: ['narration', 'advertisement', 'upbeat', 'manifestation'], description: 'Upbeat American voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/631bf5a20c2d45ffacc1311eb5dec41f/voices/N8RXoLEWQWUCCrT8uDK7/dLj63di7zBNH8XeVNQaH.mp3', samplePath: '' },
  { id: 'female-f-14', name: 'Jiya', elevenLabsId: '9bpnwGOgwzQRzNoX6rYQ', gender: 'female', ageRange: 'young', accent: 'Indian', language: 'English', category: 'Female', useCases: ['narration', 'narrative_story', 'relaxed', 'manifestation'], description: 'Relaxed Indian voice, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/9bpnwGOgwzQRzNoX6rYQ/o7dSex6DczTgBGhSo0g1.mp3', samplePath: '' },
  { id: 'female-f-15', name: 'Veronica', elevenLabsId: 'Zg5uAMn2AyrBAbtY7Ivp', gender: 'female', ageRange: 'middle', accent: 'Canadian', language: 'English', category: 'Female', useCases: ['narration', 'narrative_story', 'raspy', 'manifestation'], description: 'Raspy Canadian voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/dd49363dfccd48f3baa1c714e29ca5eb/voices/Zg5uAMn2AyrBAbtY7Ivp/2687b28d-1b92-453b-81d5-2cbfe636d538.mp3', samplePath: '' },

  { id: 'male-m-01', name: 'Declan', elevenLabsId: '1BfrkuYXmEwp8AWqSLWk', gender: 'male', ageRange: 'senior', accent: 'Irish', language: 'English', category: 'Male', useCases: ['narration', 'characters_animation', 'raspy', 'manifestation'], description: 'Raspy Irish voice, seasoned', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/MS6Mxddh07TBpCsHhuIsJsYQ8MO2/voices/1BfrkuYXmEwp8AWqSLWk/ulb2hKdFEwf6GfRlJyRK.mp3', samplePath: '' },
  { id: 'male-m-02', name: 'Joe', elevenLabsId: 'qA5SHJ9UjGlW2QwXWR7w', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Male', useCases: ['narration', 'characters_animation', 'confident', 'manifestation'], description: 'Confident American voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/qA5SHJ9UjGlW2QwXWR7w/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiJiMjEwOTQxNmM3NTE0NDQ5YTVmMDY1NDBkMTBmMGU3MyIsImZpbGVuYW1lIjoib21OWFQ3NTdmalhJZktQUXJUU3AubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'male-m-03', name: 'Countdown', elevenLabsId: 'mKoqwDP2laxTdq1gEgU6', gender: 'male', ageRange: 'senior', accent: 'American', language: 'English', category: 'Male', useCases: ['narration', 'characters_animation', 'classy', 'manifestation'], description: 'Classy American voice, seasoned', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/b2109416c7514449a5f06540d10f0e73/voices/mKoqwDP2laxTdq1gEgU6/pF4zZdr2bxDZVzs092vI.mp3', samplePath: '' },
  { id: 'male-m-04', name: 'Jerry', elevenLabsId: 'MDLAMJ0jxkpYkjXbmG4t', gender: 'male', ageRange: 'senior', accent: 'American', language: 'English', category: 'Male', useCases: ['narration', 'characters_animation', 'pleasant', 'manifestation'], description: 'Pleasant American voice, seasoned', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/ckwIURo2ELSVl0fOTOiU9bdtf143/voices/MDLAMJ0jxkpYkjXbmG4t/ZMqtCT5hEkJGti2Z2EXB.mp3', samplePath: '' },
  { id: 'male-m-05', name: 'Ed', elevenLabsId: 'dHd5gvgSOzSfduK4CvEg', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Male', useCases: ['narration', 'characters_animation', 'hyped', 'manifestation'], description: 'Hyped American voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/b2109416c7514449a5f06540d10f0e73/voices/dHd5gvgSOzSfduK4CvEg/EsJ1guwcm6nEhLK5N1Aq.mp3', samplePath: '' },
  { id: 'male-m-06', name: 'Jerry American', elevenLabsId: 'rHWSYoq8UlV0YIBKMryp', gender: 'male', ageRange: 'young', accent: 'American', language: 'English', category: 'Male', useCases: ['narration', 'characters_animation', 'chill', 'manifestation'], description: 'Chill American voice, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/ckwIURo2ELSVl0fOTOiU9bdtf143/voices/rHWSYoq8UlV0YIBKMryp/9HasPMoCRXfvlQp2HFS9.mp3', samplePath: '' },
  { id: 'male-m-07', name: 'Knox', elevenLabsId: 'cgLpYGyXZhkyalKZ0xeZ', gender: 'male', ageRange: 'young', accent: 'American', language: 'English', category: 'Male', useCases: ['narration', 'characters_animation', 'excited', 'manifestation'], description: 'Excited American voice, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/86b67cb8189f444d877f87233dbdaef6/voices/cgLpYGyXZhkyalKZ0xeZ/uxmxeudTJHZnIZ9rJ45w.mp3', samplePath: '' },
  { id: 'male-m-08', name: 'Tarquin', elevenLabsId: '7cOBG34AiHrAzs842Rdi', gender: 'male', ageRange: 'middle', accent: 'British', language: 'English', category: 'Male', useCases: ['narration', 'characters_animation', 'professional', 'manifestation'], description: 'Professional British voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/SxKc9zakkgexS9VDBHJYgFlTi272/voices/7cOBG34AiHrAzs842Rdi/hO2k7QHEYyqbRfVr8ddt.mp3', samplePath: '' },
  { id: 'male-m-09', name: 'Brad', elevenLabsId: 'MYiFAKeVwcvm4z9VsFAR', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Male', useCases: ['narration', 'characters_animation', 'serious', 'manifestation'], description: 'Serious American voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/b2109416c7514449a5f06540d10f0e73/voices/MYiFAKeVwcvm4z9VsFAR/nS1rh5Fybd6xZRbs1HdM.mp3', samplePath: '' },
  { id: 'male-m-10', name: 'Chris', elevenLabsId: '2vubyVoGjNJ5HPga4SkV', gender: 'male', ageRange: 'middle', accent: 'Boston', language: 'English', category: 'Male', useCases: ['narration', 'characters_animation', 'confident', 'manifestation'], description: 'Confident Boston voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/6b07b64edd2f4829b22ebecb2c59ac2e/voices/2vubyVoGjNJ5HPga4SkV/Wy7oFXI6MpMNBX6vK3XD.mp3', samplePath: '' },
  { id: 'male-m-11', name: 'Kai', elevenLabsId: 'Ori1rnHIeeysIxrsFZ2X', gender: 'male', ageRange: 'middle', accent: 'Australian', language: 'English', category: 'Male', useCases: ['narration', 'entertainment_tv', 'casual', 'manifestation'], description: 'Casual Australian voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/Ori1rnHIeeysIxrsFZ2X/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoiVDloVkxkek93RVlaNGZHM042VEV1dHEzbVdpMiIsImZpbGVuYW1lIjoiNUI4b1A4UEd5SmxDWDBQY21NR2EubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'male-m-12', name: 'Haseeb', elevenLabsId: 'dllHSct4GokGc1AH9JwT', gender: 'male', ageRange: 'young', accent: 'Canadian', language: 'English', category: 'Male', useCases: ['narration', 'entertainment_tv', 'upbeat', 'manifestation'], description: 'Upbeat Canadian voice, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/dllHSct4GokGc1AH9JwT/JXj5A2pcLMsfU01VbiHN.mp3', samplePath: '' },
  { id: 'male-m-13', name: 'John', elevenLabsId: 'IQjnnInWsKbdAesop75D', gender: 'male', ageRange: 'middle', accent: 'Irish', language: 'English', category: 'Male', useCases: ['narration', 'social_media', 'neutral', 'manifestation'], description: 'Neutral Irish voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/IQjnnInWsKbdAesop75D/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoiQ2loblhBM3lDdFpFTmNEdnRlYU1EVDRuY0QxMyIsImZpbGVuYW1lIjoiYWIzYWU2MDQtODkzOS00YzkzLWE1MWEtYzQyOWRhZjRlYzQ0Lm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },
  { id: 'male-m-14', name: 'Rory', elevenLabsId: 'hmMWXCj9K7N5mCPcRkfC', gender: 'male', ageRange: 'young', accent: 'Irish', language: 'English', category: 'Male', useCases: ['narration', 'conversational', 'upbeat', 'manifestation'], description: 'Upbeat Irish voice, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/hmMWXCj9K7N5mCPcRkfC/p1ZEJWYCCLVegTokk8KC.mp3', samplePath: '' },
  { id: 'male-m-15', name: 'Patrick', elevenLabsId: 'qwaVDEGNsBllYcZO1ZOJ', gender: 'male', ageRange: 'middle', accent: 'Irish', language: 'English', category: 'Male', useCases: ['narration', 'informative_educational', 'confident', 'manifestation'], description: 'Confident Irish voice, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/KTa76nXaIidZHLHMJdUUmjIvxl72/voices/qwaVDEGNsBllYcZO1ZOJ/b5f2ca62-a071-4d7b-8ec5-c9843c07ba73.mp3', samplePath: '' },

  { id: 'mys-m-01', name: 'Brady', elevenLabsId: 'kmjgtnoB3DMXA9wZpudu', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'narrative_story', 'intense', 'manifestation'], description: 'Intense American narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/kmjgtnoB3DMXA9wZpudu/IgUGFv7wGkodqrbGeZmq.mp3', samplePath: '' },
  { id: 'mys-m-02', name: 'Deep', elevenLabsId: 'QhHNJKW7n5VCJm12Xq1F', gender: 'male', ageRange: 'young', accent: 'American', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'narrative_story', 'deep', 'manifestation'], description: 'Deep American narrator, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/QhHNJKW7n5VCJm12Xq1F/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiIwNDc3ZmY4MTc1ODk0MzUzOWY3NjZiOTE4NDBhYWQwZiIsImZpbGVuYW1lIjoic25RZDZ6TVU0ZWFvVTNXdHlwSW4ubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'mys-m-03', name: 'Connery', elevenLabsId: 'vLZJLcQMJCqxjrHGEVDO', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'entertainment_tv', 'deep', 'manifestation'], description: 'Deep American narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/vLZJLcQMJCqxjrHGEVDO/eHwHEP3Bu8CkEcGmzjUL.mp3', samplePath: '' },
  { id: 'mys-m-04', name: 'Havoc', elevenLabsId: 'dtVZnErhiiosqofxDzSH', gender: 'male', ageRange: 'middle', accent: 'US Southern', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'narrative_story', 'intense', 'manifestation'], description: 'Intense US Southern narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/dANAa6fHEEdAKqePAIrHFL68dNk1/voices/dtVZnErhiiosqofxDzSH/ObDuglXZggZf6TlQsLcA.mp3', samplePath: '' },
  { id: 'mys-m-05', name: 'Caelan', elevenLabsId: '482uNsgswFPs3grclyBu', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'characters_animation', 'deep', 'manifestation'], description: 'Deep American narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/482uNsgswFPs3grclyBu/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoidXNlcl80NTAxa2RtcGt4aHhmeTU5em1nNWt2NnpndjluIiwiZmlsZW5hbWUiOiJybHhwcVNMOEx3d09oODFyaGZTSS5tcDMiLCJ0aW1lc3RhbXAiOjE3ODA4MTU2MDAwMDAwMDB9', samplePath: '' },
  { id: 'mys-m-06', name: 'Ranbir', elevenLabsId: 'MgKG6W05zBkvXijkNguO', gender: 'male', ageRange: 'middle', accent: 'Indian', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'entertainment_tv', 'deep', 'manifestation'], description: 'Deep Indian narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/MgKG6W05zBkvXijkNguO/RZQJxJd83yjl3RJGSewb.mp3', samplePath: '' },
  { id: 'mys-m-07', name: 'Austin', elevenLabsId: 'Bj9UqZbhQsanLzgalpEG', gender: 'male', ageRange: 'middle', accent: 'US Southern', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'characters_animation', 'deep', 'manifestation'], description: 'Deep US Southern narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/86b67cb8189f444d877f87233dbdaef6/voices/Bj9UqZbhQsanLzgalpEG/9c5qiVCfOXnvMEAJJmxJ.mp3', samplePath: '' },
  { id: 'mys-m-08', name: 'Darkness', elevenLabsId: 'yftckXjSEXI25jG6Ead9', gender: 'male', ageRange: 'senior', accent: 'American', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'characters_animation', 'deep', 'manifestation'], description: 'Deep American narrator, seasoned', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/yftckXjSEXI25jG6Ead9/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiIyNjIzY2YyNTI4NGU0ODcwOTdjNmMxZDY3ZDIwOGM5ZSIsImZpbGVuYW1lIjoiMWZlMzcxNWYtZTM3ZS00ZWRmLWE4Y2MtNjZmMDQwZGI3NWQyLm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },
  { id: 'mys-m-09', name: 'Sterling', elevenLabsId: 'XaRY1hVbOF8v4zmguHdl', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'characters_animation', 'deep', 'manifestation'], description: 'Deep American narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/106e1021a7ed4f449e1be8b0c1c3c16d/voices/XaRY1hVbOF8v4zmguHdl/8121dc90-004d-4284-80c8-9c92546934ae.mp3', samplePath: '' },
  { id: 'mys-m-10', name: 'Victor', elevenLabsId: 'CVP7d0EDsPO8YR2fweYp', gender: 'male', ageRange: 'middle', accent: 'German', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'characters_animation', 'deep', 'manifestation'], description: 'Deep German narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/42e4d30a6e964546ade309947a20dfa0/voices/CVP7d0EDsPO8YR2fweYp/ryVxyKkQgPF5b1rG7zCj.mp3', samplePath: '' },
  { id: 'mys-m-11', name: 'Dark', elevenLabsId: '2W8HrWcBFzCEf5cQQdIL', gender: 'male', ageRange: 'middle', accent: 'Indian', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'entertainment_tv', 'deep', 'manifestation'], description: 'Deep Indian narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/e5bfe039d3df4c5caee73869712096b3/voices/2W8HrWcBFzCEf5cQQdIL/abDUjwPTnzIohUzLPdOS.mp3', samplePath: '' },
  { id: 'mys-m-12', name: 'Rinoy', elevenLabsId: 'SHni3SZjw4bGtj6ec911', gender: 'male', ageRange: 'middle', accent: 'Indian', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'narrative_story', 'deep', 'manifestation'], description: 'Deep Indian narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/c481d93a369d409ea5e990d22fa379d2/voices/SHni3SZjw4bGtj6ec911/M6RaasWDgJR6XUw4dQs3.mp3', samplePath: '' },
  { id: 'mys-f-01', name: 'Kristen', elevenLabsId: 'Qbw4VpyUrHEG7NigKzty', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'characters_animation', 'intense', 'manifestation'], description: 'Intense American narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/Qbw4VpyUrHEG7NigKzty/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoiZHBzU2ZDNFlzQVJhaGdSZVZZSUpHMG1GZGt1MSIsImZpbGVuYW1lIjoiZjM0MzE0YTAtMTViNy00YWE5LWI4NWYtNTJjYTNhNTJlZDA0Lm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },
  { id: 'mys-f-02', name: 'Agatha', elevenLabsId: 'HH3kybY6uEJ2ebSa9Vy3', gender: 'female', ageRange: 'senior', accent: 'American', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'characters_animation', 'intense', 'manifestation'], description: 'Intense American narrator, seasoned', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/HH3kybY6uEJ2ebSa9Vy3/c3z8IJ9kFi3i78Pw3fkS.mp3', samplePath: '' },
  { id: 'mys-f-03', name: 'The', elevenLabsId: 'JOnv6J5lI68yC4Vk6udZ', gender: 'female', ageRange: 'middle', accent: 'British RP', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'narrative_story', 'intense', 'manifestation'], description: 'Intense British RP narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/user_0401kew6fghkenm8rvn6z63vytee/voices/JOnv6J5lI68yC4Vk6udZ/ae5e5872-69f3-446f-91cc-dd7a4d2aa178.mp3', samplePath: '' },
  { id: 'mys-f-04', name: 'Yuki', elevenLabsId: 'DiHqGqDdN8tWkUxlsPeg', gender: 'female', ageRange: 'middle', accent: 'Japanese', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'characters_animation', 'calm', 'manifestation'], description: 'Calm Japanese narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/DiHqGqDdN8tWkUxlsPeg/f8T7Iw8QhQJNjfMauZFg.mp3', samplePath: '' },
  { id: 'mys-f-05', name: 'Carol', elevenLabsId: '7dEuJHhweR5AFXA4INkB', gender: 'female', ageRange: 'middle', accent: 'British', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'entertainment_tv', 'calm', 'manifestation'], description: 'Calm British narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/7dEuJHhweR5AFXA4INkB/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoiMGlGTlhsUXo0Y1JqdzZ4TkM3YmZKcjJKZWdMMiIsImZpbGVuYW1lIjoiVmd4V2dmZ2VtcXc4czB2QTZYSmMubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'mys-f-06', name: 'Tessa', elevenLabsId: 'USEQXnsXRJlw2k9LUzG4', gender: 'female', ageRange: 'middle', accent: 'British', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'characters_animation', 'deep', 'manifestation'], description: 'Deep British narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/ALqfGQvfmpaWu4h31YukjCGTOtE2/voices/USEQXnsXRJlw2k9LUzG4/YnlHtYCwYaFd8vgK4TY9.mp3', samplePath: '' },
  { id: 'mys-f-07', name: 'Vivien', elevenLabsId: 'sssn4wp3AspuK2kvy3Ym', gender: 'female', ageRange: 'young', accent: 'American', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'characters_animation', 'intense', 'manifestation'], description: 'Intense American narrator, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/QGxwtfx4WtZs6nzSVZ2IGfhnUDy2/voices/sssn4wp3AspuK2kvy3Ym/r5ajru2yhSI4HjKXeEYm.mp3', samplePath: '' },
  { id: 'mys-f-08', name: 'Warm', elevenLabsId: 'mOGjJSRKsUEhB5VBEqsp', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Mysterious', useCases: ['mysterious', 'narrative_story', 'calm', 'manifestation'], description: 'Calm American narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/mOGjJSRKsUEhB5VBEqsp/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiI5OWJmMmZkMTVhZDM0YzNjYjA5ODlkZGM1NzMyZmNjMyIsImZpbGVuYW1lIjoiUXRzVnJCajhpZDNKTWFwQnZ1QU4ubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },

  { id: 'his-m-01', name: 'Dr', elevenLabsId: 'gPiEpcKoaZywgOzc0Zn9', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Historical', useCases: ['historical', 'informative_educational', 'professional', 'manifestation'], description: 'Professional American narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/2acbe644dc9144dc84ceaaba7734b4b2/voices/gPiEpcKoaZywgOzc0Zn9/JVzl4o67YJz1Cd2Vbwye.mp3', samplePath: '' },
  { id: 'his-m-02', name: 'Keith', elevenLabsId: 'uLfPT2jUO3X81OwnftBP', gender: 'male', ageRange: 'middle', accent: 'British RP', language: 'English', category: 'Historical', useCases: ['historical', 'narrative_story', 'confident', 'manifestation'], description: 'Confident British RP narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/4de200f13227453387997e4a59b5a6d2/voices/uLfPT2jUO3X81OwnftBP/cOjdzKLgMXdD7E7jUsFJ.mp3', samplePath: '' },
  { id: 'his-m-03', name: 'Russell', elevenLabsId: 'NYC9WEgkq1u4jiqBseQ9', gender: 'male', ageRange: 'middle', accent: 'British', language: 'English', category: 'Historical', useCases: ['historical', 'entertainment_tv', 'serious', 'manifestation'], description: 'Serious British narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/NYC9WEgkq1u4jiqBseQ9/cK07157YMomRml8se448.mp3', samplePath: '' },
  { id: 'his-m-04', name: 'Justin', elevenLabsId: 'tJG2ZSOV1NzFs52wkbUv', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Historical', useCases: ['historical', 'informative_educational', 'confident', 'manifestation'], description: 'Confident American narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/601d3f79a35e4f459c28b1c633ade0e9/voices/tJG2ZSOV1NzFs52wkbUv/f8fe614f-31f7-437e-9c6e-c882255aed1e.mp3', samplePath: '' },
  { id: 'his-m-05', name: 'David', elevenLabsId: 'EaCGZNIZYoLgxVzmLOPI', gender: 'male', ageRange: 'middle', accent: 'British', language: 'English', category: 'Historical', useCases: ['historical', 'informative_educational', 'formal', 'manifestation'], description: 'Formal British narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/user_6201ke27q93ffs3bm9rc756j6dg1/voices/EaCGZNIZYoLgxVzmLOPI/79c7d8b3-279c-424c-82f0-52bbdc45c5d0.mp3', samplePath: '' },
  { id: 'his-m-06', name: 'Marcus', elevenLabsId: '6WjhCXzqp2hnSqFtrG8P', gender: 'male', ageRange: 'middle', accent: 'Canadian', language: 'English', category: 'Historical', useCases: ['historical', 'informative_educational', 'professional', 'manifestation'], description: 'Professional Canadian narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/jYio1iu8xvMBRIA2SPXEKtWyiKC2/voices/6WjhCXzqp2hnSqFtrG8P/sOwljeO0E6wuzxjSBuJ2.mp3', samplePath: '' },
  { id: 'his-m-07', name: 'Adam', elevenLabsId: 'U5UjeJMsOvyhYhXfZdvZ', gender: 'male', ageRange: 'senior', accent: 'Scottish', language: 'English', category: 'Historical', useCases: ['historical', 'narrative_story', 'crisp', 'manifestation'], description: 'Crisp Scottish narrator, seasoned', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/U5UjeJMsOvyhYhXfZdvZ/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoiZGh3Mlp6V1J2d2JRa2g3dVBJS1FFRDJxY25sMiIsImZpbGVuYW1lIjoicUJaemlUQ3JhM1liSWlGV0NjbEgubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'his-m-08', name: 'Cameron', elevenLabsId: 'NOpwXiXLWfbN5KhzBTFW', gender: 'male', ageRange: 'middle', accent: 'South African', language: 'English', category: 'Historical', useCases: ['historical', 'narrative_story', 'confident', 'manifestation'], description: 'Confident South African narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/NOpwXiXLWfbN5KhzBTFW/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoiY2hTMWExMzJIeFRvWk9TZGtVelJxUUZvOWt5MSIsImZpbGVuYW1lIjoiMmJjYTMxMDQtMGJmMC00M2UxLTlmYmQtODEyNWM1YWIxM2VmLm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },
  { id: 'his-m-09', name: 'Jax', elevenLabsId: 'iB0m5bo5Htdz0t9yE0xq', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Historical', useCases: ['historical', 'entertainment_tv', 'classy', 'manifestation'], description: 'Classy American narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/eoqtemVCJRMIS3LmtYxogNS214G2/voices/iB0m5bo5Htdz0t9yE0xq/2hpNzMs3gjgYgJPVOU6p.mp3', samplePath: '' },
  { id: 'his-m-10', name: 'Kempy', elevenLabsId: 'h3DRPfZTD0Z1BwDc142N', gender: 'male', ageRange: 'middle', accent: 'British', language: 'English', category: 'Historical', useCases: ['historical', 'narrative_story', 'professional', 'manifestation'], description: 'Professional British narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/8eed4688e3af463a84b62f06d10583a9/voices/h3DRPfZTD0Z1BwDc142N/d0776ea7-6a1d-4b86-aaaa-3a0b8311b109.mp3', samplePath: '' },
  { id: 'his-m-11', name: 'Patrick', elevenLabsId: 'lcDjPH5uMz9D85TM5h2g', gender: 'male', ageRange: 'middle', accent: 'Australian', language: 'English', category: 'Historical', useCases: ['historical', 'narrative_story', 'formal', 'manifestation'], description: 'Formal Australian narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/y7gsym0FcDbtf1NJkFbNJyVqCqC2/voices/lcDjPH5uMz9D85TM5h2g/c1982e38-0135-47ec-a253-58be86ea6c60.mp3', samplePath: '' },
  { id: 'his-m-12', name: 'Nightfall', elevenLabsId: '3TTKYlYj1FFtGcSNKlJv', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Historical', useCases: ['historical', 'informative_educational', 'crisp', 'manifestation'], description: 'Crisp American narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/6Ywh4s0MNuQiYi8UmhdVhYkprfT2/voices/3TTKYlYj1FFtGcSNKlJv/dMLhGsji1n15w9nBATKO.mp3', samplePath: '' },
  { id: 'his-m-13', name: 'Anuraag', elevenLabsId: 'VaV3OXU1Zhj6G9MFdq6O', gender: 'male', ageRange: 'middle', accent: 'Indian', language: 'English', category: 'Historical', useCases: ['historical', 'narrative_story', 'professional', 'manifestation'], description: 'Professional Indian narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/VaV3OXU1Zhj6G9MFdq6O/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiI0ODgwNDhmOGJjNzA0YjJmYjgzOWY3ZjJmYWRiZjRkMSIsImZpbGVuYW1lIjoiYmVxbkdyZEpFc2t6eFc0Q1JjaUsubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'his-m-14', name: 'Jim', elevenLabsId: 'tXxkePQsw0G69D8VeDzp', gender: 'male', ageRange: 'middle', accent: 'British', language: 'English', category: 'Historical', useCases: ['historical', 'narrative_story', 'professional', 'manifestation'], description: 'Professional British narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/tXxkePQsw0G69D8VeDzp/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiIxM2E2ZmZhMDE2NWQ0MThmOGVhZjNlODhhYTUwYTY5NSIsImZpbGVuYW1lIjoicG02UmhkcU42RG9zUFpvaHdYZ1oubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'his-f-01', name: 'Bonita', elevenLabsId: '35im5K6KF9Yv03kAcZFL', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Historical', useCases: ['historical', 'informative_educational', 'confident', 'manifestation'], description: 'Confident American narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/35im5K6KF9Yv03kAcZFL/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoiUHlqRm9yeFdhR05maVJYQ2k4N3JOQm5SakZKMiIsImZpbGVuYW1lIjoiOThkMmY5ZjgtMGZkYi00MzcxLTkyODAtMGY4NTc0ZmQxNGVhLm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },
  { id: 'his-f-02', name: 'Huda', elevenLabsId: 'HHJcozd8AgLT2VmACyDV', gender: 'female', ageRange: 'middle', accent: 'Indian', language: 'English', category: 'Historical', useCases: ['historical', 'narrative_story', 'confident', 'manifestation'], description: 'Confident Indian narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/ead100df20fe48d3b1b7cccd9ee9b629/voices/HHJcozd8AgLT2VmACyDV/e205bf44-e75c-45d4-9a65-e661e21ea839.mp3', samplePath: '' },
  { id: 'his-f-03', name: 'My', elevenLabsId: 'XJVfsOvSwUXluggMM5Jj', gender: 'female', ageRange: 'middle', accent: 'Canadian', language: 'English', category: 'Historical', useCases: ['historical', 'informative_educational', 'confident', 'manifestation'], description: 'Confident Canadian narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/XJVfsOvSwUXluggMM5Jj/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiIwODJkNDMyM2E3MDQ0N2MzOWVkMzg3OWRhNWY0NTA3YSIsImZpbGVuYW1lIjoiakUwRVg2VW01NkFqQ2toSmZEWUEubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'his-f-04', name: 'Jane', elevenLabsId: 'Br4MqB57uC425pYfq0mP', gender: 'female', ageRange: 'middle', accent: 'New Zealand', language: 'English', category: 'Historical', useCases: ['historical', 'narrative_story', 'confident', 'manifestation'], description: 'Confident New Zealand narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/Br4MqB57uC425pYfq0mP/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiIwY2Q4MmMzMmY4YjA0NDE0YWUyYjE3YTdjYTRmYTA2ZCIsImZpbGVuYW1lIjoiOTk2Yjc3NzktNGNkMy00ZGJmLWE1ODItM2ExN2JhNDRkMWNiLm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },
  { id: 'his-f-05', name: 'Deborah', elevenLabsId: 'lVpo6IOLjDX4LxkYRZyj', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Historical', useCases: ['historical', 'narrative_story', 'confident', 'manifestation'], description: 'Confident American narrator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/9ef82927ee58462fa9429ef93abe605d/voices/lVpo6IOLjDX4LxkYRZyj/zG2ffkeUUTVPvZwhhr2o.mp3', samplePath: '' },
  { id: 'his-f-06', name: 'Kim', elevenLabsId: 'WaZvG31xdUW4gMSPq7Ud', gender: 'female', ageRange: 'senior', accent: 'African American', language: 'English', category: 'Historical', useCases: ['historical', 'narrative_story', 'formal', 'manifestation'], description: 'Formal African American narrator, seasoned', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/c03b1882af014577bfb4c6660ef8b1e0/voices/WaZvG31xdUW4gMSPq7Ud/bfad7f13-b678-482c-abc9-f6aeedb5e691.mp3', samplePath: '' },

  { id: 'bib-m-01', name: 'Shardul', elevenLabsId: 'KlhjbO6ojVZPbMdaYohO', gender: 'male', ageRange: 'middle', accent: 'Indian', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'deep', 'manifestation'], description: 'Deep Indian orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/KlhjbO6ojVZPbMdaYohO/jsAPTOy1QW9T91JM7h4q.mp3', samplePath: '' },
  { id: 'bib-m-02', name: 'Victor', elevenLabsId: 'U1nBX3lzKSM937PaYYfk', gender: 'male', ageRange: 'senior', accent: 'British', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'deep', 'manifestation'], description: 'Deep British orator, seasoned', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/0bef4667c08f4209abf1d88fcd140393/voices/U1nBX3lzKSM937PaYYfk/CxEkOprLWXTf6z2PQxim.mp3', samplePath: '' },
  { id: 'bib-m-03', name: 'Luke', elevenLabsId: '0ctHipTscpgE8IXfSmNN', gender: 'male', ageRange: 'middle', accent: 'New Zealand', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'deep', 'manifestation'], description: 'Deep New Zealand orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/4zOBCBZRWlYMPWOTAdxcvK14quw1/voices/0ctHipTscpgE8IXfSmNN/ZUrnDMuhIdGJLuU7Kz60.mp3', samplePath: '' },
  { id: 'bib-m-04', name: 'Joseph', elevenLabsId: 'oFoV1sxkPgfSMBqWZKyp', gender: 'male', ageRange: 'middle', accent: 'US Southern', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'deep', 'manifestation'], description: 'Deep US Southern orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/3567578f963d4b80a7c70d4c528e3f77/voices/oFoV1sxkPgfSMBqWZKyp/b924fd3f-5733-4f4f-991a-c9edf3b2f819.mp3', samplePath: '' },
  { id: 'bib-m-05', name: 'David', elevenLabsId: 'cCYjmrGZaI86GUJ7F2Nn', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'serious', 'manifestation'], description: 'Serious American orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/cCYjmrGZaI86GUJ7F2Nn/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiJhMjY2ZjQ0ZDg1MDU0NDhkOGZmNzdmMjc1Mzc5M2I3YiIsImZpbGVuYW1lIjoiaFUwbDVGTDVXUWUzVkVwUklYVmEubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'bib-m-06', name: 'Mani', elevenLabsId: 'HUGrrwnVKECouyf6wSZZ', gender: 'male', ageRange: 'middle', accent: 'Indian', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'deep', 'manifestation'], description: 'Deep Indian orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/HUGrrwnVKECouyf6wSZZ/pVMy7LvU1hfIigyHRvSe.mp3', samplePath: '' },
  { id: 'bib-m-07', name: 'Sekou', elevenLabsId: 'Tar3VOTqUrIW205XlnAi', gender: 'male', ageRange: 'middle', accent: 'South African', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'deep', 'manifestation'], description: 'Deep South African orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/3GyeMVqzQHZzHEVfaWj6QRLHd9l1/voices/Tar3VOTqUrIW205XlnAi/amMno5GMey40Rg81cQdk.mp3', samplePath: '' },
  { id: 'bib-m-08', name: 'Jason', elevenLabsId: 'lNJnJjn1OFKWTmtR1fcn', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'calm', 'manifestation'], description: 'Calm American orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/20064080b53d4ed3abb129b750e8be15/voices/lNJnJjn1OFKWTmtR1fcn/spyNL8dQ6RhC4EVoMNn3.mp3', samplePath: '' },
  { id: 'bib-m-09', name: 'Andy', elevenLabsId: 'vvVtX7DIkIyxoRO82cCc', gender: 'male', ageRange: 'middle', accent: 'British', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'calm', 'manifestation'], description: 'Calm British orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/56313bfda9ef46edb0f6d604efccadb0/voices/vvVtX7DIkIyxoRO82cCc/L28Y8Woi9Lxkif8Ofz92.mp3', samplePath: '' },
  { id: 'bib-m-10', name: 'Sekou South', elevenLabsId: 'tJvgmaVM5tDwPVrtn8TA', gender: 'male', ageRange: 'middle', accent: 'South African', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'deep', 'manifestation'], description: 'Deep South African orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/tJvgmaVM5tDwPVrtn8TA/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiJkY2U3NWY3NmM5NDc0NjU1OTU1ZWI5ZGE3ZGE3ZGM5ZiIsImZpbGVuYW1lIjoiMmUyNjYxMmQtZDMzZC00MDk4LWFlYmMtYmY1ZWUzYTRlNDI3Lm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },
  { id: 'bib-m-11', name: 'Sekou South', elevenLabsId: '3CXhjuOwoUO854fMNdkd', gender: 'male', ageRange: 'middle', accent: 'South African', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'deep', 'manifestation'], description: 'Deep South African orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/3CXhjuOwoUO854fMNdkd/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoiMUFnMWI5cXRGelpOVzNGbjF3ZTdnYkJuVERzMSIsImZpbGVuYW1lIjoieXNwVzYzb0pUV3RNdGU0UzlFYjEubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'bib-m-12', name: 'Ember', elevenLabsId: '37i69iUK8H0KcGuz48hE', gender: 'male', ageRange: 'middle', accent: 'British', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'calm', 'manifestation'], description: 'Calm British orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/80cc1b4e8db94eea90afb1c3550faa20/voices/37i69iUK8H0KcGuz48hE/xTvHuOTJFWB5py4IrgvE.mp3', samplePath: '' },
  { id: 'bib-m-13', name: 'Krob', elevenLabsId: 'oJzgkoQ7LmT0ZgjBMIGq', gender: 'male', ageRange: 'middle', accent: 'US Southern', language: 'English', category: 'Biblical', useCases: ['biblical', 'advertisement', 'deep', 'manifestation'], description: 'Deep US Southern orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/4a19c478dc594a0d9f4dbadf2ce98cc0/voices/oJzgkoQ7LmT0ZgjBMIGq/U8iaIiErxF838gieX77U.mp3', samplePath: '' },
  { id: 'bib-m-14', name: 'John', elevenLabsId: '7FroLDTDG92jPfUW6BlQ', gender: 'male', ageRange: 'middle', accent: 'US Southern', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'calm', 'manifestation'], description: 'Calm US Southern orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/SnIXs2M9LPfdEeTST87LeL65XUm2/voices/7FroLDTDG92jPfUW6BlQ/UZGYBEOFg8cxiHcrPB3R.mp3', samplePath: '' },
  { id: 'bib-f-01', name: 'Mother', elevenLabsId: 'TLeBnGDqmcwGf936zZyW', gender: 'female', ageRange: 'middle', accent: 'US Midwest', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'calm', 'manifestation'], description: 'Calm US Midwest orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/89d81636838d4bdebf508b03ccc5e823/voices/TLeBnGDqmcwGf936zZyW/bUT1LFzcmJ6fNQ2crAwm.mp3', samplePath: '' },
  { id: 'bib-f-02', name: 'Meshell', elevenLabsId: '4uXpMV2FG1JKkCQKIdSH', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'calm', 'manifestation'], description: 'Calm American orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/8056b54e83da45558cc23d05c93f0bc4/voices/4uXpMV2FG1JKkCQKIdSH/672f6512-bb98-49c7-b731-eea53e8ec524.mp3', samplePath: '' },
  { id: 'bib-f-03', name: 'Ash', elevenLabsId: '5cNLoTeeCs6bcULmXR21', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'calm', 'manifestation'], description: 'Calm American orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/8015662f666e42e393bdde0fb096b8f7/voices/5cNLoTeeCs6bcULmXR21/62070a5f-c996-4d42-900c-cb1354973392.mp3', samplePath: '' },
  { id: 'bib-f-04', name: 'Dimple', elevenLabsId: '3j4ho1lEv9BwEfkcecK2', gender: 'female', ageRange: 'middle', accent: 'Indian', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'calm', 'manifestation'], description: 'Calm Indian orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/9d2cd8e14d934aa69aeb477a85c7c4ff/voices/3j4ho1lEv9BwEfkcecK2/XjBGRyFnBh8QHEgTLm9Q.mp3', samplePath: '' },
  { id: 'bib-f-05', name: 'Laura', elevenLabsId: '3b8fXc91YHS1i2DYAlBQ', gender: 'female', ageRange: 'middle', accent: 'Irish', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'calm', 'manifestation'], description: 'Calm Irish orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/user_4001keydqszmfqhscce0yde3b01q/voices/3b8fXc91YHS1i2DYAlBQ/AGRj2ypEhOuct1oo4oXz.mp3', samplePath: '' },
  { id: 'bib-f-06', name: 'Clodagh', elevenLabsId: '9f9KY15dSvN8oi5shT8z', gender: 'female', ageRange: 'middle', accent: 'Irish', language: 'English', category: 'Biblical', useCases: ['biblical', 'narrative_story', 'calm', 'manifestation'], description: 'Calm Irish orator, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/9f9KY15dSvN8oi5shT8z/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoiNXU0Y05ZNGJCR2NZYmJSR1hJNTlhT1QzUGYzMyIsImZpbGVuYW1lIjoiNDhkYmI2ZjgtNTVmMC00YzlmLWE4NjgtOGFhNDMxODg2YTYwLm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },

  { id: 'mot-m-01', name: 'Jerry', elevenLabsId: 'oHB9Xhox1bqMl1Tvkmel', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Motivational', useCases: ['motivational', 'advertisement', 'confident', 'manifestation'], description: 'Confident American coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/oHB9Xhox1bqMl1Tvkmel/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiI1ZjcxNDgxYTNmMWU0NGQzOGE0YmI5ZmZkMjM1ZWE4YSIsImZpbGVuYW1lIjoiNFhBcGphSG5jNEVsandHY2dGVjAubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'mot-m-02', name: 'Jim', elevenLabsId: 'isPBwir9PGVoRncT0vZa', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Motivational', useCases: ['motivational', 'advertisement', 'confident', 'manifestation'], description: 'Confident American coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/fiTZSTYP5AMl6G2MNb8fVGuzMi22/voices/isPBwir9PGVoRncT0vZa/DWHG7uaExZWjogvVZMBz.mp3', samplePath: '' },
  { id: 'mot-m-03', name: 'Marcus', elevenLabsId: 'F3hPNAbHQ6mTZdjfgZdb', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Motivational', useCases: ['motivational', 'social_media', 'confident', 'manifestation'], description: 'Confident American coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/F3hPNAbHQ6mTZdjfgZdb/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiI2ZWU3NWEyOWVkOTM0YzljODlmMTg0ZmU2NDAyOTFlYiIsImZpbGVuYW1lIjoid09CMGVZN2pzV0dad2drU1Z3bjkubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'mot-m-04', name: 'Sean', elevenLabsId: 'a6o2F12lM0DO2eZ4hAj7', gender: 'male', ageRange: 'middle', accent: 'African American', language: 'English', category: 'Motivational', useCases: ['motivational', 'advertisement', 'confident', 'manifestation'], description: 'Confident African American coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/93072f44307448ee9433cd0a90656032/voices/a6o2F12lM0DO2eZ4hAj7/fd665364-b780-4c3f-a9c7-bf05eb26d44f.mp3', samplePath: '' },
  { id: 'mot-m-05', name: 'Captain', elevenLabsId: 'U0xH5XqH9N0NawL9bdEo', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Motivational', useCases: ['motivational', 'advertisement', 'confident', 'manifestation'], description: 'Confident American coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/gZiPJ4XvPyank4m6aSXGcASkXl12/voices/U0xH5XqH9N0NawL9bdEo/nz07YJ9I19dm2M98L9mN.mp3', samplePath: '' },
  { id: 'mot-m-06', name: 'Mark', elevenLabsId: 'TFNGY5E9nfgvDNh8jeHQ', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Motivational', useCases: ['motivational', 'advertisement', 'confident', 'manifestation'], description: 'Confident American coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/ab68028dc3284b0f9bbf5579200e0561/voices/TFNGY5E9nfgvDNh8jeHQ/96dc960e-ca3f-4764-a97d-dd2416d8668a.mp3', samplePath: '' },
  { id: 'mot-m-07', name: 'Krishna', elevenLabsId: 'wHhEKi6KQjJEpQ15QJaw', gender: 'male', ageRange: 'middle', accent: 'Indian', language: 'English', category: 'Motivational', useCases: ['motivational', 'social_media', 'confident', 'manifestation'], description: 'Confident Indian coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/I6jflMVgqpShp3jHrIWy8BYxL9g1/voices/wHhEKi6KQjJEpQ15QJaw/V3Ta4D7hfKmiN5CDOSmn.mp3', samplePath: '' },
  { id: 'mot-m-08', name: 'Ryan', elevenLabsId: 'WRgZjkmNCCNsWdUJ7QSt', gender: 'male', ageRange: 'young', accent: 'Indian', language: 'English', category: 'Motivational', useCases: ['motivational', 'advertisement', 'confident', 'manifestation'], description: 'Confident Indian coach, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/zrR48ObO6tdRj7KGI6ASGs9rtUf2/voices/WRgZjkmNCCNsWdUJ7QSt/UIbxzp2c1kj6J8Z0RvMz.mp3', samplePath: '' },
  { id: 'mot-m-09', name: 'Sanju', elevenLabsId: 'vf6z2FKW96ibIsWuBp5I', gender: 'male', ageRange: 'young', accent: 'Indian', language: 'English', category: 'Motivational', useCases: ['motivational', 'social_media', 'confident', 'manifestation'], description: 'Confident Indian coach, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/vf6z2FKW96ibIsWuBp5I/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiJlZDliMDVlNjMyNGM0NTc2ODU0OTAzNTJlOWExZWM5MCIsImZpbGVuYW1lIjoiMW9veWFzWjRISWhQVlBpRENQdlcubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'mot-m-10', name: 'Mike', elevenLabsId: 'x0Y0LPGWyrjIpXHcMCxT', gender: 'male', ageRange: 'middle', accent: 'Australian', language: 'English', category: 'Motivational', useCases: ['motivational', 'social_media', 'confident', 'manifestation'], description: 'Confident Australian coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/b77096b765c243638790419cd77e2a42/voices/x0Y0LPGWyrjIpXHcMCxT/ieL6JZjeqbnnvLW038fL.mp3', samplePath: '' },
  { id: 'mot-m-11', name: 'Shrey', elevenLabsId: 'Dey7SsJGQxe5rLi7TlDb', gender: 'male', ageRange: 'young', accent: 'Indian', language: 'English', category: 'Motivational', useCases: ['motivational', 'social_media', 'confident', 'manifestation'], description: 'Confident Indian coach, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/Dey7SsJGQxe5rLi7TlDb/U3MCJPk9vqSzJv5ORMF3.mp3', samplePath: '' },
  { id: 'mot-m-12', name: 'Jerry American', elevenLabsId: 'UBZMF8M0D0idRqxTQDY7', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Motivational', useCases: ['motivational', 'advertisement', 'excited', 'manifestation'], description: 'Excited American coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/5f71481a3f1e44d38a4bb9ffd235ea8a/voices/UBZMF8M0D0idRqxTQDY7/WNKpXCkiS0ShQf1tkOjC.mp3', samplePath: '' },
  { id: 'mot-m-13', name: 'Liviu', elevenLabsId: 'Q1khAM9K4Mi6p5TK0ueC', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Motivational', useCases: ['motivational', 'advertisement', 'upbeat', 'manifestation'], description: 'Upbeat American coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/nzv6QegAXCVwuS5mwHKKZJ5UY222/voices/Q1khAM9K4Mi6p5TK0ueC/3LPs19hkOHtJ4CQkFFVt.mp3', samplePath: '' },
  { id: 'mot-m-14', name: 'Jos', elevenLabsId: 'GwtqU7RCQKrjzJ0dGhqT', gender: 'male', ageRange: 'middle', accent: 'Spanish', language: 'English', category: 'Motivational', useCases: ['motivational', 'advertisement', 'confident', 'manifestation'], description: 'Confident Spanish coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/IgwDilkCraOI2af1CUCpv8HWGFt1/voices/GwtqU7RCQKrjzJ0dGhqT/082ca861-6c8e-4c81-9ea0-369788d972f5.mp3', samplePath: '' },
  { id: 'mot-m-15', name: 'Jonas', elevenLabsId: 'e6OiUVixGLmvtdn2GJYE', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Motivational', useCases: ['motivational', 'advertisement', 'upbeat', 'manifestation'], description: 'Upbeat American coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/zKCyg1LrAbOdnrZFaVH5eOjdnae2/voices/e6OiUVixGLmvtdn2GJYE/V5SYzg6Bl9B5uSNC7fV9.mp3', samplePath: '' },
  { id: 'mot-f-01', name: 'Susan', elevenLabsId: '1G3Huw0biNTSkYJGIuKP', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Motivational', useCases: ['motivational', 'advertisement', 'confident', 'manifestation'], description: 'Confident American coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/LvRQ3Gy2iMc0hiSGJtxoG9gbODk2/voices/1G3Huw0biNTSkYJGIuKP/3f184166-982c-4bfc-bb13-dbfc70029e0d.mp3', samplePath: '' },
  { id: 'mot-f-02', name: 'Laura', elevenLabsId: 'FGLJyeekUzxl8M3CTG9M', gender: 'female', ageRange: 'middle', accent: 'Spanish', language: 'English', category: 'Motivational', useCases: ['motivational', 'social_media', 'confident', 'manifestation'], description: 'Confident Spanish coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/8258346fd15d4f6cac3620289e094b10/voices/FGLJyeekUzxl8M3CTG9M/paw4kGU0kQR1ykU0Om0W.mp3', samplePath: '' },
  { id: 'mot-f-03', name: 'Jessica', elevenLabsId: 'Gvx1qZk9R4BUiBfsNPBU', gender: 'female', ageRange: 'middle', accent: 'New York', language: 'English', category: 'Motivational', useCases: ['motivational', 'social_media', 'confident', 'manifestation'], description: 'Confident New York coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/b598355580884404ac4cf90db3192e24/voices/Gvx1qZk9R4BUiBfsNPBU/qzk7Glwik1yA0tRrGNX0.mp3', samplePath: '' },
  { id: 'mot-f-04', name: 'Inspiring', elevenLabsId: 'BYifSzGNFYft5eeNKwUc', gender: 'female', ageRange: 'young', accent: 'American', language: 'English', category: 'Motivational', useCases: ['motivational', 'social_media', 'confident', 'manifestation'], description: 'Confident American coach, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/BYifSzGNFYft5eeNKwUc/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoiYnU0b0lBektIUlNSQ253OXRNcjZYSW1qVXRFMyIsImZpbGVuYW1lIjoiZmM3YmRmYzUtOWQ1ZS00MmQ3LTkxNzUtMWI0Y2M4NjBiOGMwLm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },
  { id: 'mot-f-05', name: 'Shema', elevenLabsId: 'mjac7paSiNghynEoAT9e', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Motivational', useCases: ['motivational', 'social_media', 'confident', 'manifestation'], description: 'Confident American coach, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/A81e1ICQq9dMcyi8mfVuiimlluA2/voices/mjac7paSiNghynEoAT9e/3ebe4ee6-a747-4fc7-b72d-13d47a3808a8.mp3', samplePath: '' },

  { id: 'edu-m-01', name: 'Digi', elevenLabsId: '7CdDNTvWhGFAsVrV6FXq', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'professional', 'manifestation'], description: 'Professional American speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/9fYJ15w5B6b8rnkeC0TRFFHVwVn1/voices/7CdDNTvWhGFAsVrV6FXq/rVhNOzW6XghSiF91QmoC.mp3', samplePath: '' },
  { id: 'edu-m-02', name: 'Vikrant', elevenLabsId: 'HyhAfYGa3UDZpjb4Ci4k', gender: 'male', ageRange: 'middle', accent: 'Indian', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'professional', 'manifestation'], description: 'Professional Indian speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/HyhAfYGa3UDZpjb4Ci4k/79792f28-afbe-435f-aa10-e7523316e7fe.mp3', samplePath: '' },
  { id: 'edu-m-03', name: 'Kerry', elevenLabsId: 'v4pE6K4VDU1SLgx2XnQD', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'calm', 'manifestation'], description: 'Calm American speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/5b7ab9ceaa3f43cdabcab9a3924f2c8c/voices/v4pE6K4VDU1SLgx2XnQD/16508968-4076-4229-8818-03c4776d73ce.mp3', samplePath: '' },
  { id: 'edu-m-04', name: 'Nikolay', elevenLabsId: 'inWoeNbFdezgFE6iHcxA', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'professional', 'manifestation'], description: 'Professional American speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/user_2501kdjnj0zgf98am8q8chwty21b/voices/inWoeNbFdezgFE6iHcxA/po3XmEluvQUSxIUd81kf.mp3', samplePath: '' },
  { id: 'edu-m-05', name: 'Jett', elevenLabsId: 'Jp0fPKXUBLCdWE82ol3M', gender: 'male', ageRange: 'middle', accent: 'Australian', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'professional', 'manifestation'], description: 'Professional Australian speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/tFlJRp7oAtZQnUKwyUZbj2FQ1dw1/voices/Jp0fPKXUBLCdWE82ol3M/LRoEGWwG3e768urnlqzG.mp3', samplePath: '' },
  { id: 'edu-m-06', name: 'Owen', elevenLabsId: 'ABW47xCXNNaOhg24REDc', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'pleasant', 'manifestation'], description: 'Pleasant American speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/50498b92b5f446ba9d27e2323096a947/voices/ABW47xCXNNaOhg24REDc/rxoVkifQRNt6BSwfK52d.mp3', samplePath: '' },
  { id: 'edu-m-07', name: 'Alex', elevenLabsId: 'tw43HEeA0n5kOjSqCFT9', gender: 'male', ageRange: 'middle', accent: 'British', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'calm', 'manifestation'], description: 'Calm British speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/d0e7df03d6854ce797bbdf47a7e43fc2/voices/tw43HEeA0n5kOjSqCFT9/hE8fpbhzCcUP0v29eq2j.mp3', samplePath: '' },
  { id: 'edu-m-08', name: 'Mike', elevenLabsId: 'USXpAZuBZ22GqtSpuKoQ', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'professional', 'manifestation'], description: 'Professional American speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/USXpAZuBZ22GqtSpuKoQ/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoidXNlcl81MDAxa2Y0Zmg3NWVmeHR0bW14eGo3eG13ejVrIiwiZmlsZW5hbWUiOiJhZTdlZmE4My0yYjRlLTQwOTctOWEzYi0wZjJmYWQzN2U5NGUubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'edu-m-09', name: 'Wade', elevenLabsId: '8yh4Wuya1OlwcUp0epGF', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'professional', 'manifestation'], description: 'Professional American speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/user_2601kcs6293begkrhzgjxz28xy6p/voices/8yh4Wuya1OlwcUp0epGF/8bkQaB72ZMkw5ACdmqLi.mp3', samplePath: '' },
  { id: 'edu-m-10', name: 'Gilbert', elevenLabsId: 'CNNTMtT8oo2LcWpdnuQU', gender: 'male', ageRange: 'middle', accent: 'British', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'professional', 'manifestation'], description: 'Professional British speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/T7bhqxLyENgRaSgfnqhPa6vPSID2/voices/CNNTMtT8oo2LcWpdnuQU/lwWl3qrMEin9OQVc83Zu.mp3', samplePath: '' },
  { id: 'edu-m-11', name: 'Keanan', elevenLabsId: '2fe8mwpfJcqvj9RGBsC1', gender: 'male', ageRange: 'middle', accent: 'Irish', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'professional', 'manifestation'], description: 'Professional Irish speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/qV8YKyKlq6TdmJmwYWUsdULvIkT2/voices/2fe8mwpfJcqvj9RGBsC1/pzWaX4rZXo3FPopZhNqC.mp3', samplePath: '' },
  { id: 'edu-f-01', name: 'Amara', elevenLabsId: 'IEBxKtmsE9KTrXUwNazR', gender: 'female', ageRange: 'young', accent: 'Indian', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'crisp', 'manifestation'], description: 'Crisp Indian speaker, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/IEBxKtmsE9KTrXUwNazR/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiIzOTc3YjYwNGZlMDc0MGIyYjk1Mzk4MGUwNTkyZWEwYiIsImZpbGVuYW1lIjoiSmwxZVdGV0s4eXJQTGhDZ3EwdmcubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'edu-f-02', name: 'Ana', elevenLabsId: 'jCQ8uWWBzw3HoBe23v4N', gender: 'female', ageRange: 'middle', accent: 'Croatian', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'professional', 'manifestation'], description: 'Professional Croatian speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/868b9560c9e24f7abdc4c38fee089c71/voices/jCQ8uWWBzw3HoBe23v4N/g7FT1fU4kGhKWoqiCtXO.mp3', samplePath: '' },
  { id: 'edu-f-03', name: 'Marie', elevenLabsId: 'wsL2AB1kHVzgox3WvQP2', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'professional', 'manifestation'], description: 'Professional American speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/b8ae27ff74934033b71a80133fbe3227/voices/wsL2AB1kHVzgox3WvQP2/2F2eXpat8Ab3qWESg1YW.mp3', samplePath: '' },
  { id: 'edu-f-04', name: 'Avery', elevenLabsId: 'w25dAwxibNES1hcDBvXx', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'professional', 'manifestation'], description: 'Professional American speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/9665ef086b4f4467879cb1eed8411f24/voices/w25dAwxibNES1hcDBvXx/lXz8foN9BQ6ROjlrRp0E.mp3', samplePath: '' },
  { id: 'edu-f-05', name: 'June', elevenLabsId: 'vn390rxe9PZe8VNeFuEa', gender: 'female', ageRange: 'young', accent: 'Indian', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'calm', 'manifestation'], description: 'Calm Indian speaker, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/aced48b5e15a44629ad190645dc26805/voices/vn390rxe9PZe8VNeFuEa/c770d68a-924f-4c1d-8199-941b145fbf28.mp3', samplePath: '' },
  { id: 'edu-f-06', name: 'Emma', elevenLabsId: 'D7z79vU4lfGD0bWMzJSs', gender: 'female', ageRange: 'middle', accent: 'British', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'calm', 'manifestation'], description: 'Calm British speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/6f63b9d29b754937b8a05a77baa7ec08/voices/D7z79vU4lfGD0bWMzJSs/84972fab-22d1-4af9-af73-b962273d1076.mp3', samplePath: '' },
  { id: 'edu-f-07', name: 'Ida', elevenLabsId: 'uod6Nn3FGhzBRM6gqPSU', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'calm', 'manifestation'], description: 'Calm American speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/uod6Nn3FGhzBRM6gqPSU/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiI1ZGZiZDYwYjRmZmU0NjBmYWM0ODg1MWM2NjNlNGU2ZiIsImZpbGVuYW1lIjoieEhPdlFKcmlUYnJJZFFicnF6b1IubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'edu-f-08', name: 'Claire', elevenLabsId: '6UXvJKkwaqtXE3nZHvbF', gender: 'female', ageRange: 'middle', accent: 'Australian', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'professional', 'manifestation'], description: 'Professional Australian speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/1f955fcd814f432ab74d3ab4d9ae6d80/voices/6UXvJKkwaqtXE3nZHvbF/2HZYuKGiF7qyp0P3C1MD.mp3', samplePath: '' },
  { id: 'edu-m-12', name: 'Elliot', elevenLabsId: 'ef6i5OAutcUmkyWVkRDQ', gender: 'male', ageRange: 'middle', accent: 'American', language: 'English', category: 'Educated', useCases: ['educational', 'informative_educational', 'professional', 'manifestation'], description: 'Professional American speaker, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/T7bhqxLyENgRaSgfnqhPa6vPSID2/voices/ef6i5OAutcUmkyWVkRDQ/DjSnvYZrQN76ljsKjSrs.mp3', samplePath: '' },

  { id: 'med-m-01', name: 'Barclay', elevenLabsId: 'klfO7uDt4WsjhNnhI2HZ', gender: 'male', ageRange: 'middle', accent: 'Canadian', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'calm', 'manifestation'], description: 'Calm Canadian guide, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/klfO7uDt4WsjhNnhI2HZ/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoidmkybDhQaHRDemE4YWlKbjhkT3BSM1R1QkRBMiIsImZpbGVuYW1lIjoiZTIyNDBjZjYtMGUyZi00NWVkLWJkZGMtNWFhNDBhZDViYmE2Lm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },
  { id: 'med-m-02', name: 'Stephen', elevenLabsId: 'huSf6WJX1X9lGY6I9CfQ', gender: 'male', ageRange: 'middle', accent: 'Irish', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'calm', 'manifestation'], description: 'Calm Irish guide, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/huSf6WJX1X9lGY6I9CfQ/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiJjODgyMzI3MzlkNWY0ZDRhOGViYzkyOWQwYWUzMzUzYiIsImZpbGVuYW1lIjoiMTNiMGQyZmItMTE3OS00NDg5LTg1YmUtNmI4Mjg2OGM1MmZiLm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },
  { id: 'med-m-03', name: 'Darren', elevenLabsId: '9TYDukkUVpJPDSIuv3ir', gender: 'male', ageRange: 'middle', accent: 'Irish', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'calm', 'manifestation'], description: 'Calm Irish guide, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/f55d194956f24d8b93d7015770816bc9/voices/9TYDukkUVpJPDSIuv3ir/aQAsLr1t86pKE3RPKagY.mp3', samplePath: '' },
  { id: 'med-m-04', name: 'Michael', elevenLabsId: 'g4ittRSMx8umSqUu0eGM', gender: 'male', ageRange: 'middle', accent: 'Irish', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'calm', 'manifestation'], description: 'Calm Irish guide, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/LJkuWbiMNUU1cYls8otrfgOy5tH2/voices/g4ittRSMx8umSqUu0eGM/mEM2ZrU4obBekXtbcvdZ.mp3', samplePath: '' },
  { id: 'med-m-05', name: 'Ali', elevenLabsId: '2c8AHu3t5nPsEYsszNTT', gender: 'male', ageRange: 'middle', accent: 'Canadian', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'calm', 'manifestation'], description: 'Calm Canadian guide, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/2c8AHu3t5nPsEYsszNTT/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoiZVpobXRMYUMxRk9WU2lESURJZ2VqMUwwdENBMyIsImZpbGVuYW1lIjoiMjE0OGFhN2QtZWQ0ZS00MGY0LTk5YjAtMzVmYTJmNzE0YTEyLm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },
  { id: 'med-m-06', name: 'Stryka', elevenLabsId: 'CgY1SqBRXmX1mlZzsXmR', gender: 'male', ageRange: 'middle', accent: 'Canadian', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'calm', 'manifestation'], description: 'Calm Canadian guide, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/MSx4rtGbZ1TVOxnZVS0ILpHGoId2/voices/CgY1SqBRXmX1mlZzsXmR/LwkW8hhbuJ790sKfQ23i.mp3', samplePath: '' },
  { id: 'med-m-07', name: 'Kai', elevenLabsId: '3FP8zog6uhdEdir09I9N', gender: 'male', ageRange: 'middle', accent: 'Australian', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'calm', 'manifestation'], description: 'Calm Australian guide, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/2c3a0c8801044f5686c9b2b8e850c2c8/voices/3FP8zog6uhdEdir09I9N/Q3qJU9L0dFVNsIU7sIyG.mp3', samplePath: '' },
  { id: 'med-m-08', name: 'James', elevenLabsId: 'zUbTLhK65qJM6Ic7eQj1', gender: 'male', ageRange: 'young', accent: 'South African', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'calm', 'manifestation'], description: 'Calm South African guide, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/GQ7kDGP3wJM0PLYalkhAgk5RmWG3/voices/zUbTLhK65qJM6Ic7eQj1/kCGmFTbHYTjIlpSIZfBW.mp3', samplePath: '' },
  { id: 'med-m-09', name: 'James US', elevenLabsId: 'kSvMZug5ZFM9sKGpLAei', gender: 'male', ageRange: 'young', accent: 'US Southern', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'chill', 'manifestation'], description: 'Chill US Southern guide, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/kSvMZug5ZFM9sKGpLAei/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoiUTNDZXp5alI3TWVXOXlidmpJRkJIdzdWVFc2MiIsImZpbGVuYW1lIjoiVTh0WVFJWlNxSzljSlAzMkhNTk8ubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'med-m-10', name: 'Jake', elevenLabsId: 'sTCIz7kIOkACU6JVttsD', gender: 'male', ageRange: 'middle', accent: 'British RP', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'calm', 'manifestation'], description: 'Calm British RP guide, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/VPTy0gc8BYfjqQYfOU9BZUp88c92/voices/sTCIz7kIOkACU6JVttsD/64e0a17f-6dd4-49e0-b0af-6ad84413b8b3.mp3', samplePath: '' },
  { id: 'med-f-01', name: 'Renee', elevenLabsId: 'Itr6exdQTrvjpW1lNztS', gender: 'female', ageRange: 'middle', accent: 'Canadian', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'gentle', 'manifestation'], description: 'Gentle Canadian guide, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/WCBsrlvZaaYNcIUvCfIoW5CeIF42/voices/Itr6exdQTrvjpW1lNztS/357697e8-ffca-49a4-a63c-21a58579a6bc.mp3', samplePath: '' },
  { id: 'med-f-02', name: 'Anne', elevenLabsId: 'MnXdp1RrMFboJjgMtirI', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Meditation', useCases: ['meditation', 'conversational', 'relaxed', 'manifestation'], description: 'Relaxed American guide, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/13c8c86730544e77ae80bfc90434ecc3/voices/MnXdp1RrMFboJjgMtirI/y6ExjuAgZSwK4cGd8w29.mp3', samplePath: '' },
  { id: 'med-f-03', name: 'Ms', elevenLabsId: 'DLsHlh26Ugcm6ELvS0qi', gender: 'female', ageRange: 'middle', accent: 'US Southern', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'relaxed', 'manifestation'], description: 'Relaxed US Southern guide, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: true, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/DLsHlh26Ugcm6ELvS0qi/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ1c2VyX2lkIjoidGwybnFQMWVyOFhIWkdzWHpmZU8wREd5cmJFMiIsImZpbGVuYW1lIjoiSUw3aFJtRk1CQ1JzWVFKOW04a1MubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'med-f-04', name: 'Sia', elevenLabsId: 'gGNPBRoUZm1UG9WqGVlW', gender: 'female', ageRange: 'young', accent: 'American', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'calm', 'manifestation'], description: 'Calm American guide, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/da7abb4ba538422eac832f581b5f05d3/voices/gGNPBRoUZm1UG9WqGVlW/qRSSNWiJJqcu2VHNXHjj.mp3', samplePath: '' },
  { id: 'med-f-05', name: 'Emma', elevenLabsId: 'HMsHSO9iPieho74ZXn8A', gender: 'female', ageRange: 'young', accent: 'Australian', language: 'English', category: 'Meditation', useCases: ['meditation', 'conversational', 'calm', 'manifestation'], description: 'Calm Australian guide, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/HMsHSO9iPieho74ZXn8A/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiIzZTI4OTc3N2NjYTc0YzZmOGRhZmZhMDhhYjIzZDVkYiIsImZpbGVuYW1lIjoiMGQwNTRiMDUtMGM2Ny00ZTdkLWIwMmUtMTJmYmQ3ZGI3YTM2Lm1wMyIsInRpbWVzdGFtcCI6MTc4MDgxNTYwMDAwMDAwMH0%3D', samplePath: '' },
  { id: 'med-f-06', name: 'Luna', elevenLabsId: '6rOxfAnZpbM3VIEhFaeV', gender: 'female', ageRange: 'young', accent: 'American', language: 'English', category: 'Meditation', useCases: ['meditation', 'conversational', 'calm', 'manifestation'], description: 'Calm American guide, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/1df4b21393b74964b03d3690a173eb80/voices/6rOxfAnZpbM3VIEhFaeV/3Xpm0W15PoRAh3l83lpD.mp3', samplePath: '' },
  { id: 'med-f-07', name: 'Mira', elevenLabsId: 'DVxf8tkOIac2UAoDXYVS', gender: 'female', ageRange: 'young', accent: 'British', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'calm', 'manifestation'], description: 'Calm British guide, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://api.us.elevenlabs.io/v1/voices/DVxf8tkOIac2UAoDXYVS/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiJkZjdmYzQ5YjFhNTY0ZDY2OWU5ZjczZWIyMjVlYWUxYiIsImZpbGVuYW1lIjoiMHFsTEtBWUtHM293NTF5dWhXWXIubXAzIiwidGltZXN0YW1wIjoxNzgwODE1NjAwMDAwMDAwfQ%3D%3D', samplePath: '' },
  { id: 'med-f-08', name: 'Mira British', elevenLabsId: 'zKafQapzbOjT3CDcZONC', gender: 'female', ageRange: 'young', accent: 'British RP', language: 'English', category: 'Meditation', useCases: ['meditation', 'conversational', 'calm', 'manifestation'], description: 'Calm British RP guide, young', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/8667145a4464468db4379552840d41eb/voices/zKafQapzbOjT3CDcZONC/aQhFqrz8rSFCePhk3kfG.mp3', samplePath: '' },
  { id: 'med-f-09', name: 'Eliza', elevenLabsId: 'LN3tpYiUJuhZ89dqCNG3', gender: 'female', ageRange: 'middle', accent: 'British', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'calm', 'manifestation'], description: 'Calm British guide, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/17a3b8d0cf464740ba751056efbb55db/voices/LN3tpYiUJuhZ89dqCNG3/BAXkOauaTxyr0mWdKPWn.mp3', samplePath: '' },
  { id: 'med-f-10', name: 'Amy', elevenLabsId: '49S3tHf0uTVzQN5pADIu', gender: 'female', ageRange: 'middle', accent: 'American', language: 'English', category: 'Meditation', useCases: ['meditation', 'narrative_story', 'pleasant', 'manifestation'], description: 'Pleasant American guide, mature', defaultTier: 'multilingual', supportedTiers: ['flash', 'multilingual', 'turbo'], multilingual: false, previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/f0e1d78d04c544bda0c83167c8630a02/voices/49S3tHf0uTVzQN5pADIu/822d790c-c8ae-47ee-a9f3-df3b5ed89ebd.mp3', samplePath: '' },
];

/** Ordered category list for UI tabs. */
export const VOICE_CATEGORIES = ['Female', 'Male', 'Mysterious', 'Historical', 'Biblical', 'Motivational', 'Educated', 'Meditation']
  .filter(c => VOICE_CATALOG.some(v => v.category === c));

/** Per-category character blurb shown in the picker header. */
export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  Female: 'Versatile female narrators across accents and ages.',
  Male: 'Versatile male narrators across accents and ages.',
  Mysterious: 'Deep, slow, suspenseful — cinematic narrator vibe.',
  Historical: 'Documentary narrators — authoritative and mature.',
  Biblical: 'Reverent, sermon-like — ancient gravitas.',
  Motivational: 'Energetic, coach-like — powerful and confident.',
  Educated: 'Calm, intelligent — TED-talk articulate.',
  Meditation: 'Soft, calming, ASMR-quality — breathy warmth.',
};

/** Category-appropriate preview phrases. */
export const CATEGORY_TEST_PHRASES: Record<string, string> = {
  Mysterious: 'The truth was hidden, but now it begins to surface…',
  Historical: 'In the year 1492, the world changed forever.',
  Biblical: 'And the Lord spoke unto them with great wisdom.',
  Motivational: 'You were born to win. Today is your day.',
  Educated: 'The fascinating thing about quantum entanglement is…',
  Meditation: 'Breathe in slowly… feel your body relax…',
  Male: 'Welcome to a new era of possibility.',
  Female: 'Welcome to a new era of possibility.',
};

/** All unique accents. */
export const VOICE_ACCENTS = [...new Set(VOICE_CATALOG.map(v => v.accent))].sort();

/** All unique use cases. */
export const VOICE_USE_CASES = [...new Set(VOICE_CATALOG.flatMap(v => v.useCases))].sort();

/** Lookup a voice by internal ID. */
export function getVoiceById(id: string): VoiceEntry | undefined {
  return VOICE_CATALOG.find(v => v.id === id);
}

/** ElevenLabs model_id for a given tier. */
export function modelIdForTier(tier: VoiceTier): string {
  switch (tier) {
    case 'flash': return 'eleven_flash_v2_5';
    case 'turbo': return 'eleven_turbo_v2_5';
    case 'multilingual':
    default: return 'eleven_multilingual_v2';
  }
}

/** Resolve the best tier for a given voice + user-requested tier. */
export function resolveTier(voice: VoiceEntry, requestedTier?: VoiceTier): VoiceTier {
  if (requestedTier && voice.supportedTiers.includes(requestedTier)) return requestedTier;
  return voice.defaultTier;
}

/** Speed presets exposed to users (ElevenLabs native speed param). */
export const SPEED_PRESETS = { slow: 0.85, normal: 1.0, fast: 1.15 } as const;
export type SpeedPreset = keyof typeof SPEED_PRESETS;

/** Map a speed preset name (or legacy @slower/@faster suffix) to a numeric speed. */
export function speedValue(preset?: string | number): number {
  if (typeof preset === 'number') return Math.min(1.15, Math.max(0.85, preset));
  const v = (preset || '').toLowerCase();
  if (v.includes('slow')) return SPEED_PRESETS.slow;
  if (v.includes('fast')) return SPEED_PRESETS.fast;
  return SPEED_PRESETS.normal;
}

/** Filter the catalog. All filters are AND. */
export function filterVoices(opts: {
  gender?: string;
  accent?: string;
  category?: string;
  useCase?: string;
  ageRange?: string;
  search?: string;
  multilingual?: boolean;
}): VoiceEntry[] {
  let result = VOICE_CATALOG;
  if (opts.gender) result = result.filter(v => v.gender === opts.gender);
  if (opts.accent) result = result.filter(v => v.accent === opts.accent);
  if (opts.category) result = result.filter(v => v.category === opts.category);
  if (opts.useCase) result = result.filter(v => v.useCases.includes(opts.useCase!));
  if (opts.ageRange) result = result.filter(v => v.ageRange === opts.ageRange);
  if (opts.multilingual) result = result.filter(v => v.multilingual);
  if (opts.search) {
    const q = opts.search.toLowerCase();
    result = result.filter(v =>
      v.name.toLowerCase().includes(q) ||
      v.description.toLowerCase().includes(q) ||
      v.category.toLowerCase().includes(q) ||
      v.accent.toLowerCase().includes(q) ||
      v.useCases.some(u => u.includes(q))
    );
  }
  return result;
}
